### PR TITLE
Restore self::params lookup

### PR DESCRIPTION
**Pull request by sathieu**
Needed for apt::dater.

### CODE REVIEW

**Comment by sathieu** [comment]
I can change `apt::dater` but this will break setupsusing for example `$apt_dater_package = 'myownpkg'`.

This PR works on Puppet 5 (and Puppet 4).

**Comment by alvagante** [comment]
Thank you, tested on puppet 3, it doesn't seem to work on apt::dater but it doesn't break params_lookup, which was the most important thing.

**Comment by sathieu** [comment]
Thanks. On Puppet3, I thought that [lib/puppet/parser/functions/params_lookup.rb](https://github.com/example42/puppi/blob/master/lib/puppet/parser/functions/params_lookup.rb) was used ...

**Comment by alvagante** [comment]
@sathieu oh, right of course

**Pull request merged**
